### ISSUE TITLE
white screen issue 

### ISSUE THREAD

**Issue by CIADRP** [neatodev/CityLauncher#1]
i installed the new launcher , i went to the advanced colour settings and  i choosed the log profile 2 option . I started  the game and the screen is white . Then I tried to open the launcher to turn off the new setting , but it wont open . I 've reinstalled the launcher and nothing . Then I 've uninstalled him and tried to change the setting from the old launcher but i get an error saying that tthe price for length can't be smaller than zero. Finally i 've reinstalled the game but the problem stays the same please help me . I love this game

![20221120154204_1](https://user-images.githubusercontent.com/118673393/202908751-74f73049-4d9c-4fb9-901b-991a9302dfaa.jpg)
![20221120154154_1](https://user-images.githubusercontent.com/118673393/202908759-286cb031-5a83-49d4-9f39-c8ced440fad2.jpg)

[citylauncher_report__20-11-22__03-45-38.log](https://github.com/neatodev/CityLauncher/files/10049955/citylauncher_report__20-11-22__03-45-38.log)

**Comment by neatodev** [comment]
Are you using the newest release available on [Nexusmods](https://www.nexusmods.com/batmanarkhamcity/mods/406?tab=files)?

**Comment by CIADRP** [comment]
I downloaded the HD texture pack Plus - Complete file from Nexusmods. The
launcher was already in the file

**Comment by neatodev** [comment]
Right, but that is not the most recent launcher version.
Please delete your config folder, and download the newest launcher version from [Nexusmods](https://www.nexusmods.com/batmanarkhamcity/mods/406?tab=files).

**Comment by CIADRP** [comment]
Great . Everything looks normal. Is it safe to use the same option ?
Thank you for helping me

**Comment by neatodev** [comment]
Yes, that issue has been fixed.
