### ISSUE TITLE
Can't open it

### ISSUE THREAD

**Issue by tkp206093** [neatodev/CityLauncher#2]
I change the file name and open it
Just nothing happened

and I try so many time reinstall the game in steam or reboot system 
also can't open it

Log:
https://pastebin.com/ciJrxa1D

**Comment by neatodev** [comment]
You changed the file name? What do you mean?

EDIT:

The following line in the log
`2022-12-06 23:15:03.6186|INFO|CityLauncher.IniReader|InitTexturePackFix - Texture Pack is enabled: True || Texture Pack Plus is enabled: True.`
indicates that the launcher does indeed work. You can only achieve those `true` values if you enable the settings in the launcher. Please provide more details.

**Comment by tkp206093** [comment]
I videotape for you：
https://drive.google.com/file/d/1SDneoB07P-fhugf7xpxLgQvupXVqdcJZ/view?usp=sharing

**Comment by neatodev** [comment]
Alright that's interesting.
Please send me an eventviewer report of the launcher.

To do this:
- 'Open' the launcher
- Afterwards, open Event Viewer
- Click on 'Windows Logs' and then 'Application'

There should be some sort of warning or error in there.

**Comment by tkp206093** [comment]
https://pastebin.com/0N9ceG0u
https://pastebin.com/NAVmMAq8
https://pastebin.com/hwAPpTWX

**Comment by neatodev** [comment]
This is weird. An exception gets thrown when it shouldn't, I do catch it in my code.
Please send your BmInput & UserInput ini files.

**Comment by tkp206093** [comment]
[Config.zip](https://github.com/neatodev/CityLauncher/files/10169874/Config.zip)

**Comment by tkp206093** [comment]
Oh！ Is because Fix Catwoman's Quickfire Disarm key missing on keyboard ?
https://www.pcgamingwiki.com/wiki/Batman:_Arkham_City#Fix_Catwoman.27s_Quickfire_Disarm_key_missing_on_keyboard

**Comment by neatodev** [comment]
It seems you edited the input files to manually include the catwoman disarm fix?
Simply delete BmInput & UserInput (as in: delete the files) and then run the launcher. The launcher itself has a fix for the catwoman disarm.
Let me know if that works.

**Comment by tkp206093** [comment]
Delete these two files and run the launcher is fix that.
Thank you!
