### ISSUE TITLE
Could not find 'BatmanAC.exe'

### ISSUE THREAD

**Issue by nekochan03** [neatodev/CityLauncher#3]
Hi, guys.

I recently installed the advanced launcher but, whenever I try to start the game, an error window comes up. It says: «Error! Could not find 'BatmanAC.exe'. Is the Launcher in the correct folder?», although the launcher has been installed in the correct folder (Batman Arkham City GOTY\Binaries\Win32), where the BatmanAC.exe file is.

Can someone please help me?

**Comment by neatodev** [comment]
Your game is pirated. The launcher ignores pirated copies by design.
