### ISSUE TITLE
not an issue just here to say proton works too and give how I did it

### ISSUE THREAD

**Issue by gitdunk** [neatodev/CityLauncher#5]
I followed the linux steps except replaced winetricks with `protontricks 200260` (200260 is the steam version appid). and for the registry bit used
`STEAM_COMPAT_DATA_PATH="/home/deck/.local/share/Steam/steamapps/compatdata/200260" 
"/home/deck/.steam/steam/steamapps/common/Proton 8.0/proton" runinprefix cmd`
then put the reg.exe bit in that command prompt, you have to switch the prefix to proton 4.2 for dotnet48 to install, also it pulls up winecfg several times, set windows version to xp the first time, then 7 for the rest of them (just 7 might work havent tried it) then change it back to the proton you want. the launcher will not open from the steam "configure PC Options" option, you instead need to make it launch by opening the BmLauncher under that prefix via protontricks, this command will work for people who got protontricks from the discover store/flatpak `flatpak run --command=protontricks-launch com.github.Matoking.protontricks --appid 200260 '/home/deck/steam gamedata/Batman Arkham City GOTY/Binaries/Win32/BmLauncher.exe'` (these are the steamdeck directories by the way) (sorry if this is not where to put it I barely understand github)

**Comment by gitdunk** [comment]
nevermind that somehow made me unable to launch the game at all

**Comment by gitdunk** [comment]
never mind that broke it, program wont start at all, trying again EDIT: using proton 7 works if you replace dotnet 3.5 with dotnet 4.8 manually, also the disable startup movies box is greyed out this was far too complex to have a guide set up so I would probably go for wine instead if steamdeck allowed for it.

**Comment by neatodev** [comment]
There should be no more linux issues now.

**Comment by VishLabs1** [comment]
is there a guide on how to install this on Steam with Linux (Pop OS in my case)

**Comment by neatodev** [comment]
Just replace the executable, that's it. The program works fine with recent WINE versions.
